version: '3.7'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: "nginx"
    restart: on-failure
    ports:
      - 8088:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    container_name: "php-7.4"
    volumes:
      - ./:/var/www/html:rw
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - ./database/dump:/var/lib/postgresql/data
    restart: on-failure
    container_name: "postgres"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "${DB_PORT}:${DB_PORT}"

